name: pytorch_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.11.0
  - aiohttp=3.7.3
  - args=0.1.0
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.4.13
  - cachetools=4.1.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - clint=0.5.1
  - cryptography=3.3.1
  - cudatoolkit=10.1.243
  - freetype=2.10.4
  - fsspec=0.8.5
  - future=0.18.2
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.34.0
  - idna=2.10
  - importlib-metadata=3.3.0
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - llvm-openmp=11.0.0
  - lz4-c=1.9.2
  - markdown=3.3.3
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.2.0
  - multidict=5.1.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.8
  - pillow=8.0.1
  - pip=20.3.3
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.6
  - python_abi=3.8
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.7.0
  - tk=8.6.10
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cloudpickle==1.6.0
    - colorcet==2.0.6
    - configparser==5.0.2
    - cycler==0.10.0
    - dload==0.6
    - docker-pycreds==0.4.0
    - gitdb==4.0.5
    - gitpython==3.1.14
    - imageio==2.9.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - matplotlib==3.4.2
    - numba==0.53.1
    - pandas==1.1.5
    - param==1.10.1
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.8.0
    - pyct==0.4.8
    - python-dateutil==2.8.1
    - pytorch-lightning==1.2.3
    - pytz==2020.4
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - sentry-sdk==1.0.0
    - shap==0.39.0
    - shortuuid==1.0.1
    - slicer==0.0.7
    - smmap==3.0.5
    - subprocess32==3.5.4
    - test-tube==0.7.5
    - threadpoolctl==2.1.0
    - torch==1.7.1+cu101
    - torchaudio==0.7.2
    - torchmetrics==0.3.2
    - torchvision==0.8.2+cu101
    - tqdm==4.41.0
    - wandb==0.10.22